---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-gmail-secret
  namespace: monitoring
spec:
  encryptedData:
    alertmanager-gmail-app-password: AgA7zwGahI/T7EuR8QZ30gF6X9JIjFQRwaB/IpZxXQGDkcx2lXxOpCfx5DCf2F6903sxrmFp+Mg+wiCdUKJyZxYagUSX0uzvPyC2+smctvjC22Z7W2Pf8113nqmFJ/wBUjgi4hJ/j1+Z7Bbq4DGPqQamVIxeFzBVHMaRC5vXTsQqrzd4zqswptP2lL4s5p6j2hVG4kw5skrHHfTwCsUT/ReWK3+E8sY5Aw6+kw3WIcryrrGwFYyp4ze1pKNwo4zhMFU66oxiD7jOR4okS7IuByDgED3/S5wmEZONlN+uMkgjwDaNQ67+yReEcBUxn7Geg1pxiq+Co1yMr6jrOF53hqSGadnnQfhe8FL6GYzxHTwkfY5hI36Oyd3kZEn6gl9AJgbhRqop2JkGNdV1+Jcck17q0jYeYOLmdj6O7Jf4lv1YPqPawyglPaEngFazBHkd/MixZP3BJpNF9uLz7YOw5ld4n+Xoz7DS04aITRdjYbCjiVXu/taTbMLA6vbWdxVeikXjVzt1Pm/xVwMCl282isSxESkJ9HPPZ93Hsx7++8C0PI9YibLQWd+p5g51qiG8wtoh7W4Au/LHJjL3Yyzi+9Tk97cQcNFOygm98+Rg9MYCTiD7gOgTPQkHLr0jboqVw3bzxd2bekaTsmAY7TT7nr/ZpbuORTVF/I102zUeJGuha35SdloQmj1A8qISab1hvJCPs/Wj8vNzb38At48WlpZiO7Yj
  template:
    metadata:
      name: alertmanager-gmail-secret
      namespace: monitoring
