---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: common-secret
  namespace: platform
spec:
  encryptedData:
    DB_PASSWORD: AgBuWrofdiVNC3LFsuy/b/9rRibr8NK5eZjH/kVSA2iU/jvVCMdmVYuILYPiELuniFsbJr8N3d5RFwIT4xSq8HiCG+K49yeXPUsAsyugvsdr1DG4zE1AzQK08ERCBJW4WA8GoIhs5p5VhbKtO45RBMYbdeMTtG9aE04XqSDwq/V04204n8cWScMsrwVQhjMCu5bBnFcY8Wg+N85lEya38yghGovD4WYBAGyOGd3haMYyOh6sLLlkg4xkPUhhb1CPW9PB0whiSYjVpQ+n4cjbWXd8sd52VUhV1T66eP3+JkTddH6shIFDC2SHY/xkD4ywPmNUm+DQF7G7jLSBK9eo5fXPuYJIllGg5D7sZnvJgVtGz9RUQ2Z7MkPYVNVy5PucJRz49rwgLzg6uZb3fnhBYj3/MjIK0A7ubNEdPwNyPrBcc5EOE33Bsnkv5BgGCNAYg7hnQqUEWo5Ta/ITEt1eJfxCaUz2eqx6BtgmY//MReMkTkcIuRuiBiQxSn5NBUrfgvLQjzo7nTmYzSgEFbE5uD/cDXKEPXvrz/ZD7pbdRI9s2v1t+XEIrSpy3PkTuygAhVVSO8RlDxaghQUDiOxeJZBFWRepdb6bQU6PiLg7MV5oYTns9fdjcAcKIL0ThjQDnH2tkixyTtiWnRV2q3j9V9yKBRPOg+7PL47n5GeYAz0yxjE1NSLfHD1gRQFIOsLDXvUgs1JzQS27xckk
    DB_USERNAME: AgCKR0KuExROm4z0mFPcUYonvNTceSaD3T58jVI/3HA6a7tpihEw3y1JWKP7hgH0RL1UVRPa3U/U2m2WlTdWvzqyaOSMTmvf2QX+c2xx57Kgfh1bcL5aGlQrdVl4iBkDXIFatlotbtHlyv0cNqqDCgbfLXARhfjUy8DvFXtdxOaxPOG0Uxqu8NwVpMEuLN9TeX3ffphVGYZakSw6NQADDsht1sJ7SX91Hsf+C5/WMm9pnpOX22KG/SmwonFqxjMddgVYZcM5iFXsZpRntsWZHatgqw/zLTLfx/TMPqJHnaRTfZtSNwMG5nSh7UZGdgHtG7sMnowrQxSm3O7crJCbz5fb1ZFZXzgIZnJMyjIT9J5gqn3Ei/aUm3YJih8YyIECJdo+O5gX9l+5+8kerzrnmOnTA8/GQyPsPFTAdgugPljWACBmQoX0rxwVwkGzKDUuhWujJjp7bi35VP0Ov/Ub+qRSsRlh8q66YiQfwB+TXqvq2fWC3vLLlnaB4vLjDHtz2r+HbKlr2ICMkMQf5Q5/sawn0rgIpFeYa++xELPPJMFEF4qpDpjmopamvPYIeKrx/irnDvMbV9abwh6GyL0G4QGyABGi8VjQEA5JPoOiQFvA5RYU5+ffylkss2VB5LaH8fbMnjgwOO/hDqcZjy41XsU9Db9Xu/0G7DN54TpbA+fvjbkenf/J26+RrpfWLlrp+SfVZI3KpIYJ
  template:
    metadata:
      name: common-secret
      namespace: platform
