apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
  namespace: platform
type: Opaque
stringData:
  JWT_ADMIN_SECRET: "SuperUserAdminSecretKeyMustBeAtLeast256BitsLongForJwtSigning123"
  JWT_USER_SECRET: "afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf"