resources:
- gateway-secret.yaml
- user-service-secret.yaml
- shop-service-secret.yaml
- order-service-secret.yaml
- chat-service-secret.yaml
- notification-service-secret.yaml
- superuser-service-secret.yaml