apiVersion: v1
kind: Secret

metadata:
  name: shop-service-secret
  namespace: platform

type: Opaque

stringData:
  CLOUDINARY_CLOUD_NAME: djgic5a4h

  CLOUDINARY_API_KEY: "451898683743538"

  CLOUDINARY_API_SECRET: FftdV3HUag-EUciHTHwRcxVAt0E