---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: superuser-service-secret
  namespace: platform
spec:
  encryptedData:
    INTERNAL_API_KEY: AgBtA1ZZtqUpgIWi3AlGiqedhJr1spYf3ZrpEtG5TwQaVsytfjbkSDSvClwh3JK58Q23y/9svsJApIL+2qtT0B25QdeZhEEutP5gQGAotiCGDY0KByWa32U3kclDByJa5+J6UqOpqdMZ/HR/cmSozSStTQUP7GG3OlvMb/V7gryKloeszIip8irqNT0XTbGSvBENNP+Lej8jOqcqq4o26ww9fdWS3FrPEljsnIdFABhHltdvWt2RQuIJuhrBt6NaaLMiZtG4nWnFlSKTr0AQWwJr00xWXmW2PfszRZsQ8eqAqO+NytHp+u/Yw0PeClxtxoVMytSNicj1nq4N3Jpdn6D6DeLsXq4w+42Ur2jXX6G0cafPQp0hZA6iwT0tOYnMEdn+s1tqobsYfWEYkpMyuYbJhK/OLnC5CMJwexwLNN6MjZWuA2YGv+DYTZUN4EUXum31ek/B76uQm9xpcnxEUJwUIBO9Crz1nOBS50ouF+/Ox/c8TL1RU6szV4pCYofkKLmzhjIckDts4H728rWnavgOq2LU2B/QmLvh969IM0wPXI+D9M76lial4HgYPkrJpTwM7G+Aq6zoW7CVGn3dJ5SpuenSSVg+LD5HYPro8bDKjeeyU2z804wkFt6MFn8xSatiNii3Uut6feh/Hkupzxl6bg7djfnblJ7F5RUWPs2NeuPjRl44GdOkH4zXq07hLTJVQABxc7Mbw48sGCN2rsjECIvnwQ==
    JWT_SECRET: AgAoJNmAPKFr+Fikm8QguIUCUFGTu4LSCZML4cIzinx2smT9Z6ensF/67+jPA8f+qZyUsu6gYLiECOLvXIPVnkr8Nw9Rn4d0SQFHTTEunhm61ERKD1sf7YU8WS606PNjE0e6UA0LZyMgvgX8ZpDHHYpZqigfa9qLriD7dOB9RixulBrH+5OdV8yDELmmpDPnf7M8okwbK1MCLzm70Mv43l5TvOc7IaaPSEa415xyAwesiyI0c0+WggQSFpAwIcKsHSpz+xEI/2bwWOaG7HVaUZY3JsqzJMxVlO53alfviJqHK7W9HdIaCfQl/sXPgkDEOIte5GVC/CjWUB0/JcM3jNKdKD0ak0P31YWkZeBN+nHA4lEzc1+lR8KiZ5Ncxoax19ELBS512bxa12+yFWLS0GO8khWMUYTJ1elpD3ADKx1QJo6sgbYABfuBXvza6Rtm5FMNX3fohS3gr3GY5qSvF7KHo9FMoRFNd89wTI1I2d7BbYE+KrN85N0f1bxhOGle50QsA0YfWsS7m6NCkVEXt2rV1GK9p3dsj9gS1IxQesS0SJskZHJDrdMCttWNNFtXQ1R4JNZi4DjAW49Z7VCzuGZBGMU410FToCF/yNQeE9Mv6QO95tgDls5Mir1AXP6WKONtcK/q/bNfzqUHVAZX3+oU6GUcenJMahfvcqm5hFXOj0gH6IwUyGcMGPksFB3pHVE=
  template:
    metadata:
      name: superuser-service-secret
      namespace: platform
