apiVersion: v1
kind: Secret

metadata:
  name: superuser-service-secret
  namespace: platform

type: Opaque

stringData:
  JWT_SECRET: SuperUserAdminSecretKeyMustBeAtLeast256BitsLongForJwtSigning123

  INTERNAL_API_KEY: WHOAMI_INTERNAL_2026