apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: platform

type: Opaque

stringData:
  DB_USERNAME: root
  DB_PASSWORD: password

  JWT_SECRET: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf

  SPRING_MAIL_USERNAME: whoami.amar@gmail.com
  SPRING_MAIL_PASSWORD: qzuk ppgb icwe xilm