replicaCount: 1

springProfile: kubernetes

timezone: UTC

image:
  repository: whomaiamar/gateway
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8079
  targetPort: 8079

configMap:
  enabled: true
  data:
    SPRING_APPLICATION_NAME: gateway
    SERVER_PORT: "8079"

    EUREKA_SERVER: http://service-registry-service-registry.platform.svc.cluster.local:8761/eureka/

    EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
    EUREKA_CLIENT_FETCH_REGISTRY: "true"

    MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics

    SPRING_PROFILES_ACTIVE: kubernetes

secret:
  enabled: false

serviceAccount:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "500m"
    memory: 512Mi
autoscaling:
  enabled: false

pdb:
  enabled: false

ingress:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []

podAnnotations: {}

probes:
  startup:
    path: /actuator/health/liveness
    failureThreshold: 30
    periodSeconds: 10

  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 5

  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 60
    periodSeconds: 10
