apiVersion: v1
kind: ConfigMap

metadata:
  name: chat-service-config
  namespace: platform

data:
  SPRING_APPLICATION_NAME: Servicechat

  SERVER_PORT: "8085"

  DB_URL: jdbc:mysql://mysql.database.svc.cluster.local:3306/chat