apiVersion: v1
kind: ConfigMap

metadata:
  name: notification-service-config
  namespace: platform

data:
  SPRING_APPLICATION_NAME: notification-service

  SERVER_PORT: "8087"

  DB_URL: jdbc:mysql://mysql.database.svc.cluster.local:3306/notification

  FIREBASE_CONFIG_PATH: classpath:firebase-config.json

  FIREBASE_DATABASE_URL: https://your-firebase-project.firebaseio.com

  APP_ENV: development