apiVersion: v1
kind: ConfigMap

metadata:
  name: order-service-config
  namespace: platform

data:
  SPRING_APPLICATION_NAME: OrderService

  SERVER_PORT: "8086"

  DB_URL: jdbc:mysql://mysql.database.svc.cluster.local:3306/order