apiVersion: v1
kind: ConfigMap

metadata:
  name: superuser-service-config
  namespace: platform

data:
  SPRING_APPLICATION_NAME: SuperUser

  SERVER_PORT: "8088"

  DB_URL: jdbc:mysql://mysql.database.svc.cluster.local:3306/superuser