apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: platform

data:
  SPRING_APPLICATION_NAME: USERREGISTRY
  SPRING_PROFILES_ACTIVE: kubernetes

  SERVER_PORT: "8080"

  DB_URL: jdbc:mysql://mysql.database.svc.cluster.local:3306/user

  KAFKA_SERVERS: dhondoo-kafka-kafka-bootstrap.messaging.svc.cluster.local:9092

  EUREKA_SERVER: http://service-registry-service-registry.platform.svc.cluster.local:8761/eureka/

  SPRING_JPA_HIBERNATE_DDL_AUTO: update