apiVersion: v2

name: superuser-service

description: Dhondoo Superuser Service

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:

  - name: dhondoo-common

    version: 1.0.0

    repository: file://../common