apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - applications.yaml
  - database.yaml
  - ingress.yaml
  - messaging.yaml
  - monitoring.yaml
  - platform.yaml
  - security.yaml

  - configmaps
  - secrets