apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: platform
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Amarjeetlocato/Dhondoo-To---gitops.git
    targetRevision: main
    path: environments/development/applications

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true