apiVersion: v2

name: kafka

description: Dhondoo Kafka Helm Chart

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:

  - name: dhondoo-common

    version: 1.0.0

    repository: file://../common