kube-prometheus-stack:

  crds:
    enabled: true

  prometheusOperator:

    enabled: true

    resources:

      requests:
        cpu: 250m
        memory: 256Mi

      limits:
        cpu: "1"
        memory: 1Gi

  prometheus:

    enabled: true

    prometheusSpec:

      replicas: 2

      retention: 30d

      scrapeInterval: 30s

      evaluationInterval: 30s

      serviceMonitorSelectorNilUsesHelmValues: false

      serviceMonitorSelector:

        matchLabels:
          app.kubernetes.io/part-of: dhondoo

      serviceMonitorNamespaceSelector:

        matchNames:
          - monitoring

      ruleSelectorNilUsesHelmValues: false

      ruleSelector:

        matchLabels:
          app.kubernetes.io/part-of: dhondoo

      ruleNamespaceSelector:

        matchNames:
          - monitoring

      podAntiAffinity: soft

      resources:

        requests:
          cpu: "1"
          memory: 2Gi

        limits:
          cpu: "4"
          memory: 8Gi

  alertmanager:

    enabled: true

    alertmanagerSpec:

      replicas: 2

      resources:

        requests:
          cpu: 250m
          memory: 256Mi

        limits:
          cpu: "1"
          memory: 1Gi

      podAntiAffinity: soft

  grafana:

    enabled: true

    replicas: 2

    resources:

      requests:
        cpu: 250m
        memory: 512Mi

      limits:
        cpu: "1"
        memory: 2Gi

  kubeStateMetrics:

    enabled: true

  nodeExporter:

    enabled: true

    resources:

      requests:
        cpu: 100m
        memory: 128Mi

      limits:
        cpu: 500m
        memory: 512Mi