# environments/production/values/mysql-values.yaml

replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306
  targetPort: 3306

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 50Gi
  storageClass: ""

mysql:
  database: dhondoo
  username: dhondoo

existingSecret: mysql-secret

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: "2"
    memory: 4Gi

probes:
  startup:
    enabled: true
    initialDelaySeconds: 20
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 60

  readiness:
    enabled: true
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6

  liveness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 20
    failureThreshold: 3

securityContext:
  runAsNonRoot: false

podSecurityContext: {}

terminationGracePeriodSeconds: 60

pdb:
  enabled: false

podAntiAffinity:
  enabled: false

topologySpreadConstraints:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}