replicaCount: 1

image:
  repository: whomaiamar/notification-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8087
  targetPort: 8087

configMap:
  commonName: common-config
  existingName: notification-service-config

secret:
  commonName: common-secret
  existingName: notification-service-secret

serviceAccount:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "500m"
    memory: 512Mi
autoscaling:
  enabled: false

ingress:
  enabled: false

pdb:
  enabled: false

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 60
    periodSeconds: 10

  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 5

  startup:
    path: /actuator/health
    failureThreshold: 30
    periodSeconds: 10

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []

podAnnotations: {}

securityContext:
  fsGroup: 1000
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
