{{- if .Values.serviceAccount.create }}

apiVersion: v1
kind: ServiceAccount

metadata:

  name: {{ include "dhondoo.serviceAccountName" . }}

  labels:
    {{- include "dhondoo.labels" . | nindent 4 }}

automountServiceAccountToken: false

{{- with .Values.serviceAccount.annotations }}

annotations:

{{ toYaml . | indent 2 }}

{{- end }}

{{- end }}