{{ include "dhondoo.serviceaccount" . }}

---

{{ include "dhondoo.secret" . }}

---

{{ include "dhondoo.configmap" . }}

---

{{ include "dhondoo.deployment" . }}

---

{{ include "dhondoo.service" . }}

---

{{ include "dhondoo.ingress" . }}

---

{{ include "dhondoo.hpa" . }}

---

{{ include "dhondoo.pdb" . }}