# infrastructure/kafka/kafka-nodepool.yaml
# PRODUCTION VERSION

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool

metadata:
  name: dhondoo-kafka-pool
  namespace: messaging
  labels:
    strimzi.io/cluster: dhondoo-kafka

spec:
  replicas: 3

  roles:
    - broker
    - controller

  storage:
    type: persistent-claim
    size: 100Gi
    storageClass: standard
    deleteClaim: false

  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 8Gi

  jvmOptions:
    "-Xms": "1g"
    "-Xmx": "4g"

  template:
    pod:
      metadata:
        labels:
          app: kafka

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: kafka
              topologyKey: kubernetes.io/hostname

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: kafka