apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dhondoo-kafka-pool
  namespace: messaging
  labels:
    strimzi.io/cluster: dhondoo-kafka
spec:
  replicas: 1

  roles:
    - broker
    - controller

  storage:
    type: persistent-claim
    size: 20Gi
    deleteClaim: false

  resources:
    requests:
      cpu: "500m"
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 1Gi

  jvmOptions:
    "-Xms": "256m"
    "-Xmx": "768m"

  template:
    pod:
      metadata:
        labels:
          app: kafka
