apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dhondoo-kafka-pool
  namespace: messaging
  labels:
    strimzi.io/cluster: dhondoo-kafka

spec:
  replicas: 3

  roles:
    - broker
    - controller

  storage:
    type: persistent-claim
    size: 10Gi
    storageClass: standard
    deleteClaim: false

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 768Mi

  jvmOptions:
    "-Xms": "256m"
    "-Xmx": "512m"

  template:
    pod:
      metadata:
        labels:
          app: kafka