# environments/development/values/chat-service-values.yaml

replicaCount: 1

springProfile: kubernetes
timezone: UTC

image:
  repository: whomaiamar/chat-service
  tag: 046b5ecc1a0b844a4e8c3a8d6d2bd0e3bf6a7cef
  pullPolicy: Always
<<<<<<< HEAD

service:
  type: ClusterIP
  port: 8085
  targetPort: 8085

configMap:
  commonName: common-config
  existingName: chat-service-config

secret:
  commonName: common-secret
  existingName: chat-service-secret

serviceAccount:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "500m"
    memory: 512Mi

autoscaling:
  enabled: false

pdb:
  enabled: false

ingress:
  enabled: false

topologySpreadConstraints:
  enabled: false

podAntiAffinity:
  enabled: false

probes:
  startup:
    enabled: true
    path: /actuator/health
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 36
    successThreshold: 1

  readiness:
    enabled: true
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1

  liveness:
    enabled: true
    path: /actuator/health/liveness
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 20
    failureThreshold: 3
    successThreshold: 1

terminationGracePeriodSeconds: 30

lifecycle:
  enabled: true
  preStop:
    enabled: true
    command:
      - /bin/sh
      - -c
      - sleep 5
=======
replicaCount: 1
>>>>>>> 03c25c4d302a3ec57d607f88789c14fba6417304
