# environments/development/values/kafka-values.yaml

replicaCount: 1

image:
  repository: apache/kafka
  tag: "3.8.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "500m"
    memory: 1Gi

storage:
  type: persistent-claim
  size: 10Gi
  deleteClaim: false
  class: ""

kafka:
  replicas: 1

  config:
    defaultReplicationFactor: 1
    minInsyncReplicas: 1
    offsetsTopicReplicationFactor: 1
    transactionStateLogReplicationFactor: 1
    transactionStateLogMinIsr: 1

  listeners:
    client:
      enabled: true
      port: 9092

  topics:
    autoCreate: true

  heap:
    min: 256m
    max: 512m

jmx:
  enabled: false

metrics:
  enabled: false

podAntiAffinity:
  enabled: false

topologySpreadConstraints:
  enabled: false

pdb:
  enabled: false

terminationGracePeriodSeconds: 120

nodeSelector: {}

tolerations: []

affinity: {}