# environments/development/values/user-service-values.yaml

replicaCount: 1

springProfile: kubernetes
timezone: UTC

image:
  repository: whomaiamar/user-registry
  tag: 575c1da539c365f73a4a4d869bf40449017bf716
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

configMap:
  commonName: common-config
  existingName: user-service-config

secret:
  commonName: common-secret
  existingName: user-service-secret

serviceAccount:
  create: true

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "500m"
    memory: 1Gi

autoscaling:
  enabled: false

pdb:
  enabled: false

ingress:
  enabled: false

topologySpreadConstraints:
  enabled: false

podAntiAffinity:
  enabled: false

probes:
  startup:
    enabled: true
    path: /actuator/health
    initialDelaySeconds: 30
    timeoutSeconds: 5
    periodSeconds: 5
    failureThreshold: 60
    successThreshold: 1

  readiness:
    enabled: true
    path: /actuator/health/readiness
    initialDelaySeconds: 10
    timeoutSeconds: 5
    periodSeconds: 10
    failureThreshold: 6
    successThreshold: 1

  liveness:
    enabled: true
    path: /actuator/health/liveness
    initialDelaySeconds: 60
    timeoutSeconds: 5
    periodSeconds: 20
    failureThreshold: 3
    successThreshold: 1

terminationGracePeriodSeconds: 30

lifecycle:
  enabled: true
  preStop:
    enabled: true
    command:
      - /bin/sh
      - -c
      - sleep 5